### ISSUE TITLE
PyPi update

### ISSUE THREAD

**Issue by Phyks** [sciunto/tear-pages#3]
Hi,

PyPDF2 does not seem to be indicated as a dependency for this package on PyPi.

Plus, I have 
```
      assert tag == supported_tags[0]
  AssertionError
```

when trying to install it with Python3 on Arch.

Could you update the PyPi infos and `setup.py` accordingly please?

Thanks!

**Comment by sciunto** [comment]
For your error, I solved the problem by upgrading wheel in my venv.

**Comment by Phyks** [comment]
Sorry for the delay, I did not have any internet access last week.

```
% pip install wheel --upgrade
[…]
Successfully installed wheel-0.26.0

 % pip install tear-pages     
Collecting tear-pages
  Using cached tear-pages-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-bkfhhycp/tear-pages/setup.py", line 4, in <module>
        from tearpages import __version__
      File "/tmp/pip-build-bkfhhycp/tear-pages/tearpages.py", line 9, in <module>
        from PyPDF2 import PdfFileWriter, PdfFileReader
    ImportError: No module named 'PyPDF2'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bkfhhycp/tear-pages
```

And:

```
% pip install pypdf2
Collecting pypdf2
Installing collected packages: pypdf2
Successfully installed pypdf2-1.25.1

% pip install tear-pages  
Collecting tear-pages
  Using cached tear-pages-0.2.2.tar.gz
Collecting PyPDF>=1.25.1 (from tear-pages)
  Could not find a version that satisfies the requirement PyPDF>=1.25.1 (from tear-pages) (from versions: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13)
No matching distribution found for PyPDF>=1.25.1 (from tear-pages)
```
